### ISSUE TITLE
Web Accessibility Standards

### ISSUE THREAD

**Issue by sanjusunny** [amazon-connect/amazon-connect-chat-interface#41]
Hello team, is the chat interface (or ChatJS) compliant with specific web accessibility standards (e.g. WCAG 2.0 AA)? I do see aria tags in the code but wanted to check if this is part of the formal feature set? Thanks.

**Comment by xiajohn** [comment]
This is not part of the formal feature set. We try our best to be in compliant but some things can be missed.

**Comment by haomingli2020** [comment]
Hi @sanjusunny, we have accessibility auditing for our internal chat-interface package and plan to work on those improvements in the future. But we don't have an ETA for making this repo compliant yet. 
Can you help me understand your use case and what concerns you have?

**Comment by sanjusunny** [comment]
Thanks, it was less about a specific use case and more about providing AWS
customers a stronger starting point to help them create a more accessible
experience for their customers.

**Comment by spencerlepine** [comment]
Hi @sanjusunny, team will provide the details about accessibility in the README file going forward. These changes will be added in PR https://github.com/amazon-connect/amazon-connect-chat-interface/pull/124.

Since there are no further action items we are taking specific to this issue, I am going to resolve.

Thanks,
Spencer
